FROM python:3.7

WORKDIR /code

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY configs/config.ini config.ini
COPY grants_tagger/train.py train.py

ENTRYPOINT ["python", "train.py", "--config", "config.ini", "--cloud"]
